const crypto=require('crypto'),fs=require('fs'),path=require('path');
const ADMIN_KEY=process.env.ADMIN_KEY||'093kboap', SECRET=process.env.SECRET||'seth-room-pro-secret';
function sign(d){return crypto.createHmac('sha256',SECRET).update(d).digest('base64url')}
function makeToken(role,min){const exp=Date.now()+Number(min)*60*1000,p={role,exp,iat:Date.now()};const d=Buffer.from(JSON.stringify(p)).toString('base64url');return {token:d+'.'+sign(d),exp}}
function verify(t){if(!t||!t.includes('.'))return null;const [d,s]=t.split('.');if(sign(d)!==s)return null;try{const p=JSON.parse(Buffer.from(d,'base64url').toString('utf8'));return Date.now()<=p.exp?p:null}catch{return null}}
function page(title,body){return `<!DOCTYPE html><html lang="zh-Hant"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>${title}</title><style>*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at top,#1c1018,#07070b 70%);color:white;font-family:"Microsoft JhengHei",Arial;padding:20px}.wrap{max-width:1180px;margin:auto}.top{display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid #ff1f16;padding-bottom:16px;margin-bottom:22px}.box{background:#12121a;border:1px solid #3b3039;border-radius:14px;padding:28px;margin-bottom:18px;box-shadow:0 18px 50px rgba(0,0,0,.45)}h1{margin:0;font-size:34px}.pink{color:#ff1f16}.login{max-width:430px;margin:12vh auto}h2{text-align:center}label{display:block;margin:18px 0 8px}input,select{width:100%;padding:16px;border-radius:8px;border:1px solid #b72a73;background:#111;color:white;font-size:17px}button,a.btn{display:inline-block;border:0;border-radius:8px;background:linear-gradient(90deg,#b30f08,#ff62ad);color:white;padding:15px 28px;font-size:17px;font-weight:800;text-decoration:none;cursor:pointer}.red{background:#dc3545!important}.center{text-align:center}.muted{color:#aaa}.row{display:grid;grid-template-columns:1fr auto;gap:14px}code{display:block;background:#111;padding:16px;border:1px solid #b72a73;border-radius:8px;word-break:break-all;color:#ff1f16}.footer{text-align:center;color:#ff1f16;margin-top:28px;font-weight:900}@media(max-width:700px){.top{display:block}.row{grid-template-columns:1fr}}</style></head><body>${body}</body></html>`}
module.exports=async(req,res)=>{const url=new URL(req.url,'https://'+req.headers.host),pathname=url.pathname;
if(pathname==='/'||pathname==='/admin'){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(page('AI賽特選房後台',`<div class="login box"><h2>AI賽特選房輔助器 PRO</h2><div class="center muted">後台金鑰登入</div><form method="POST" action="/admin/login"><label>金鑰：</label><input name="adminKey" placeholder="請輸入金鑰"><button style="width:100%;margin-top:18px" type="submit">登入</button></form></div>`))}
if(pathname==='/admin/login'&&req.method==='POST'){const body=await getBody(req);if(body.adminKey!==ADMIN_KEY){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(page('登入失敗',`<div class="login box center"><h2>金鑰錯誤</h2><a class="btn" href="/admin">返回</a></div>`))}res.statusCode=302;res.setHeader('Location','/manage?adminKey='+encodeURIComponent(ADMIN_KEY));return res.end()}
if(pathname==='/manage'){if(url.searchParams.get('adminKey')!==ADMIN_KEY){res.statusCode=302;res.setHeader('Location','/admin');return res.end()}res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(page('後台管理',manageHtml(ADMIN_KEY)))}
if(pathname==='/create'&&req.method==='POST'){const body=await getBody(req);if(body.adminKey!==ADMIN_KEY){res.statusCode=302;res.setHeader('Location','/admin');return res.end()}const minutes=Math.max(5,Math.min(1440,Number(body.minutes||60))),role=body.role||'玩家',made=makeToken(role,minutes),link=`https://${req.headers.host}/vip/${encodeURIComponent(made.token)}`,expireAt=new Date(made.exp).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'});res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(page('已產生分享網址',manageHtml(ADMIN_KEY,link,role,minutes,expireAt)))}
if(pathname.startsWith('/vip/')){const token=decodeURIComponent(pathname.replace('/vip/','')),payload=verify(token);if(!payload){res.statusCode=403;res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(page('連結無效',`<div class="login box center"><h2>連結已過期或無效</h2><p class="muted">請聯繫冥界高級VIP重新開通</p><a class="btn" href="/admin">返回</a></div>`))}let file=fs.readFileSync(path.join(process.cwd(),'public','app.html'),'utf8');file=file.replace('</body>',`<script>history.replaceState(null,'','?exp=${payload.exp}');</script></body>`);res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(file)}
res.statusCode=404;res.end('404')}
function manageHtml(adminKey,link='',role='玩家',minutes=60,expireAt=''){return `<div class="wrap"><div class="top"><h1><span class="pink">AI</span>賽特選房 後台管理</h1><div>Unknown（agent） <a class="btn red" href="/admin" style="margin-left:12px">登出</a></div></div><div class="box"><form method="POST" action="/create"><input type="hidden" name="adminKey" value="${adminKey}"><label>角色：</label><select name="role"><option value="玩家">玩家</option><option value="代理">代理</option><option value="測試">測試</option></select><label>時效(分鐘)：</label><input name="minutes" value="${minutes}" type="number" min="5" max="1440"><div class="center" style="margin-top:26px"><button type="submit">🔗 產生會員分享網址</button></div></form></div>${link?`<div class="box"><h2 class="pink">已產生分享網址</h2><label>專屬網址</label><div class="row"><code id="shareLink">${link}</code><button onclick="copyLink()">複製</button></div><p>角色：${role}　時效：${minutes} 分鐘　到期：${expireAt}</p><p class="muted">會員點擊網址即可直接進入 AI 賽特選房輔助器。</p></div><script>function copyLink(){navigator.clipboard.writeText(document.getElementById("shareLink").innerText);alert("已複製分享網址")}</script>`:''}<div class="footer">冥界高級VIP</div></div>`}
function getBody(req){return new Promise(resolve=>{let data='';req.on('data',c=>data+=c);req.on('end',()=>{const p=new URLSearchParams(data),o={};for(const [k,v]of p.entries())o[k]=v;resolve(o)})})}